ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
path('addtocart/<int:i>',views.add_to_cart,name="addtocart"),
    path('cartview',views.cart_view,name="cartview"),
    path('cartremove/<int:i>',views.cart_remove,name="cartremove"),
    path('cartdelete/<int:i>',views.cart_delete,name="cartdelete"),
    path('orderform',views.orderform,name="orderform"),
    path('status/<u>',views.payment_status,name="status"),
    path('order_view',views.order_view,name="order_view"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name='search'
urlpatterns = [
    path('',views.search_products,name="search"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [
   path('',views.allcategories,name="categories"),
   path('products/<int:p>',views.allproducts,name="products"),
   path('details/<int:p>',views.productdetails,name="details"),
   path('register', views.register, name="register"),
   path("login", views.user_login, name="login"),
   path("logout", views.user_logout, name="logout"),
   path('addcat',views.addcategory,name="addcat"),
   path('addpro', views.addproduct, name="addpro"),
   path('addstock/<int:p>',views.addstock,name="addstock"),

]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product


from django.contrib.auth.models import User



class Cart(models.Model): #Cart Table definition
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_added=models.DateTimeField(auto_now_add=True)















    def subtotal(self):
        return self.product.price*self.quantity


class Order_details(models.Model):
      product=models.ForeignKey(Product,on_delete=models.CASCADE)
      user=models.ForeignKey(User,on_delete=models.CASCADE)
      no_of_items=models.IntegerField()
      address=models.TextField()
      phone_no=models.BigIntegerField()
      pin=models.IntegerField()

      order_id=models.CharField(max_length=20,blank=True)
      ordered_date=models.DateTimeField(auto_now_add=True)

      payment_status=models.CharField(max_length=20,default="pending")
      delivery_status=models.CharField(max_length=20,default="pending")

class Payment(models.Model):
    name=models.CharField(max_length=100)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=30,blank=True)
    razorpay_payment_id=models.CharField(max_length=30,blank=True)
    paid=models.BooleanField(default=False)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from cart.models import Cart,Payment,Order_details
from django.contrib.auth import login
from django.views.decorators.csrf import csrf_exempt
from shop.models import Product
from django.contrib.auth.models import User
import razorpay
@login_required
def add_to_cart(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(user=u,product=p)  #checks the product  present in Cart table for a particular user
        if(p.stock>0):
            c.quantity+=1                    #if present it will increment the quantity of product
            c.save()
            p.stock-=1
            p.save()
    except:
        if(p.stock>0):#if not present then it will create a new record inside cart table with quantity=1
            c=Cart.objects.create(product=p,user=u,quantity=1)
            c.save()
            p.stock-=1
            p.save()
    return redirect('cart:cartview')
@login_required
def cart_view(request):
    u=request.user
    total=0

    c=Cart.objects.filter(user=u) #All cart items for a particular user
    print(c)
    for i in c:
        total+=i.quantity*i.product.price  #Calculates the sum of each product price*quantity


    context={'cart':c,'total':total}
    return render(request,'cart.html',context)

@login_required
def cart_remove(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(user=u,product=p)
        if(c.quantity>1):
            c.quantity-=1
            c.save()
            p.stock+=1
            p.save()
        else:
            c.delete()
            p.stock += 1
            p.save()
    except:
        pass

    return redirect('cart:cartview')

@login_required
def cart_delete(request,i):
    u=request.user
    p=Product.objects.get(id=i)
    try:
        c=Cart.objects.get(user=u,product=p)
        c.delete()
        p.stock+=c.quantity
        p.save()
    except:
        pass
    return redirect('cart:cartview')
@login_required
def orderform(request):
    if(request.method=="POST"):
        address=request.POST['a']
        phone=request.POST['p']
        pin=request.POST['pi']
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.quantity*i.product.price
        total=int(total*100)
        client=razorpay.Client(auth=('rzp_test_dVrWySYZeHoiH1','MIKQkSGzNErgrSyoUtlPqiwQ')) #Creates a client connection
        #using razorpay id and secret code

        response_payment=client.order.create(dict(amount=total,currency="INR"))#creates an order with
        # razorpay using razorpay client
        # print(response_payment)
        order_id=response_payment['id']  #Retrieves the order_id from response
        order_status=response_payment['status']#retrieves status from response
        if(order_status=="created"): #if status is created then store order_id in Payment and Order_details table
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()
            for i in c: #For each item craetes a record inside Order_details table
                o=Order_details.objects.create(product=i.product,user=u,no_of_items=i.quantity,address=address,phone_no=phone,pin=pin,order_id=order_id)
                o.save()
        else:
            pass
        response_payment['name']=u.username  #additional information name

        context={'payment':response_payment}
        return render(request,'payment.html',context)

    return render(request,'orderform.html')



from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def payment_status(request,u):
    user = User.objects.get(username=u)
    if(not request.user.is_authenticated): #if user is not authenticated
        login(request,user) #allowing request user to login

    if(request.method=="POST"):
        response=request.POST
        print(response)



        param_dict={
            'razorpay_order_id':response['razorpay_order_id'],
            'razorpay_payment_id':response['razorpay_payment_id'],
            'razorpay_signature':response['razorpay_signature']
        }

        client = razorpay.Client(auth=('rzp_test_dVrWySYZeHoiH1', 'MIKQkSGzNErgrSyoUtlPqiwQ')) #To create a razorpay client
        print(client)
        try:
            status=client.utility.verify_payment_signature(param_dict) #to check the authenticity of the razorpay signature
            print(status)

            #To retrieve a particular record in Payment Table whose order id matches the response order id
            p=Payment.objects.get(order_id=response['razorpay_order_id'])
            p.razorpay_payment_id=response['razorpay_payment_id'] #adds the payment id after suceesful payment
            p.paid=True #changes the paid status to True
            p.save()


            print(user.username)
            o=Order_details.objects.filter(user=user,order_id=response['razorpay_order_id']) #retrieve the records in order_details
            #matching with current user and response order_id
            print(o)
            for i in o:
                i.payment_status="paid"
                i.save()

            #After succsesful payment deletes the items in cart for a particular user
            c=Cart.objects.filter(user=user)
            c.delete()


        except:
            pass

    return render(request, 'payment_status.html',{'status':status})

@login_required
def order_view(request):
    u=request.user
    o=Order_details.objects.filter(user=u,payment_status="paid")
    context={'orders':o}
    return render(request,'order_view.html',context)

ecommerce/search/views.py
from django.shortcuts import render

from shop.models import Product

from django.db.models import Q

def search_products(request):
    query=""
    p=None
    if(request.method=="POST"):
        query=request.POST['q']

        if(query):
            p=Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))
            print(p)
    return render(request,'search.html',{'product':p,'q':query})

ecommerce/templates/addcategory.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}

    {% endblock %}
{% block content %}
<center>
    <div class="container mt-5 p-3" style="margin-bottom:100px;">
<h2 class="text-center">Add Category Details</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
  <label  class="form-label">Name</label>
  <input type="text" class="form-control" name="n" placeholder="Enter Category name">
</div>
 <div class="mb-3">
  <label  class="form-label">Image</label>
  <input type="file" class="form-control" name="i">
</div>
     <div class="mb-3">
   <label  class="form-label">Description</label>
  <textarea class="form-control" name="d">Write Category Description</textarea>
</div>

     <div class="mb-3">

  <input type="submit" class="form-control">
</div>
</form>
 </div>
{% endblock %}
</body>
</html>

ecommerce/templates/addstock.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}

    {% endblock %}
{% block content %}
<center>
    <div class="container mt-5 p-3 w-25" style="margin-bottom:100px;">
<h2 class="text-center">Add stock Details</h2>
<form method="post">
    {% csrf_token %}
    <div class="mb-3">

  <input type="number" class="form-control" value="{{pro.stock}}" name="n" placeholder="Enter stock">
</div>

     <div class="mb-3">

  <input type="submit" class="form-control">
</div>
</form>
 </div>
{% endblock %}
</body>
</html>

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<header>
<div class="container-fluid text-center mt-3 mb-4">
    <img src="{% static 'images/logo1.jpg' %}" class="rounded-circle" height="100px" width="110px">
</div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mt-1">
  <div class="container-fluid">
    <a class="navbar-brand fs-3 fw-bold" href="#">Myshop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 fs-5 fw-bold">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:categories' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Allcategories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:products' i.id %}">{{i.name}}</a></li>
          {% endfor %}
          </ul>
        </li>
          {% if user.is_authenticated %}
          {% if user.is_superuser == False %}   <!--normal user -->
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa fa-shopping-cart fs-3" aria-hidden="true"></i><sup class="mx-2 fs-5">{{c}}</sup></a>
        </li>
           <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'cart:order_view' %}">Your Orders</a>
        </li>

          {% else %}
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:addcat' %}">Add Categories</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:addpro' %}">Add Products</a>
        </li>
         {% endif %}

            <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% else %}
   <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
         {% endif %}
      </ul>
      <form class="d-flex" method="post" action="{% url 'search:search' %}">
        {% csrf_token %}
        <input class="form-control me-2 border border-dark" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
<div class="container-fluid">
{% block content %}
{% endblock %}
</div>

<div class="footer pt-1 mt-5">
    <p class="text-center fs-5"><i class="fa fa-copyright me-1" aria-hidden="true"></i>myshop@pvt.ltd</p>
</div>

</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5 p-3" style="margin-bottom:100px;">
        <div class="row text-light">
            <h2 class="text-center fw-bold mb-5">Shopping Cart</h2>
            <div class="col-7">
                <table class="table table-bordered shadow text-light">
                <tr>
                    <th colspan="6" class="text-center fs-5">Cart Items</th>
                </tr>

                    {% for i in cart %}
                    <tr class="fs-6 fw-bold text-center">
                        <td class="p-3"><img src="{{i.product.image.url}}" height="100px" width="100px"></td>
                        <td class="p-3">{{i.product.name}}</td>
                        <td class="p-3">Unit price:{{i.product.price}}<br>
                            Quantity:{{i.quantity}}</td>
                        <td class="p-3">Subtotal:{{i.subtotal}}</td>
                        <td class="pt-3">
                            {% if i.product.stock > 0 %}
                            <a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa fa-plus-circle fs-5 text-light mx-1" aria-hidden="true"></i></a>
                            <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa fa-minus-circle fs-5 text-light mx-1" aria-hidden="true"></i></a>
                            <a href="{% url 'cart:cartdelete' i.product.id %}"><i class="fa fa-trash fs-5 text-light mx-1" aria-hidden="true"></i></a>
                        {% else %}
                         <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa fa-minus-circle fs-5 text-light mx-1" aria-hidden="true"></i></a>
                            <a href="{% url 'cart:cartdelete' i.product.id %}"><i class="fa fa-trash fs-5 text-light mx-1" aria-hidden="true"></i></a>
                        {% endif %}

                        </td>


                    </tr>
                 {% endfor %}

                </table>
            </div>

            <div class="col-4 ms-5">
                <table class="table table-bordered text-light fs-5">
                <tr>
                    <th colspan="4" class="text-center p-4">Check Out</th>
                </tr>
                    <tr class="text-center">
                        <td class="p-4"><b>Total Price:{{total}}</b></td>
                    </tr>
                </table>
                <div class="d-flex justify-content-between fw-bold mt-5">
                <a href="{% url 'cart:orderform' %}" class="btn btn-dark text-light">Order Now</a>
                <a href="{% url 'shop:categories' %}" class="btn btn-dark text-light">Continue Shopping</a></div>
            </div>

        </div>


{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="row mt-3">
        <div class="col-12">
    <img src="{% static 'images/banner.jpg' %}" height="400px" width="100%"></div>
</div>

<div class="row mt-3 px-3" style="margin-bottom:100px">
    <div class="col-12">
        <h1 class="text-center fw-bold text-light mt-5 mb-5">Our Collections</h1>

        <p style="text-align:justify;line-height:2.5;" class="fs-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
    </div>
</div>

<div class="container mt-5" style="margin-bottom:100px">

    <div class="row">
{% for i in cat %}
        <div class="col-sm-4">
            <div class="card mx-auto border border-3 border-light" style="width: 20rem;">
  <img src="{{i.image.url}}"  height="200px" width="100%" class="card-img-top" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title mb-3">{{i.name}}</h5>

    <a href="{% url 'shop:products' i.id %}" class="btn btn-secondary px-5 mb-2 fs-5">Products</a>
  </div>
</div></div>


{% endfor %}

    </div>

</div>




{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="container mt-5" style="margin-bottom:100px;">
   <div class="card mb-3 mx-auto" style="max-width: 70%;">
  <div class="row g-0">
    <div class="col-md-4 p-3">
      <img src="{{product.image.url}}" class="rounded-start"  height="400px" width="100%" alt="...">
    </div>
    <div class="col-md-8 mt-4 p-3">
      <div class="card-body">
        <h2 class="card-title">{{product.name}}</h2>
        <h5>{{product.price}}</h5>
        <h5>{{product.stock}}</h5>
        <h4>Product Details</h4>
        <p class="card-text" style="line-height:2;text-align:justify">{{product.desc}}</p>
          {% if user.is_superuser == True %}
            {% if product.stock > 0 %}
          <h5>Product In stock</h5>
           <a href="{% url 'shop:addstock' product.id %}" class="btn btn-secondary fw-bold mt-3 mb-2 texy-center">ADD STOCK</a>
          {% else %}
          <h5>Product Out of stock</h5>
           <a href="{% url 'shop:addstock' product.id  %}" class="btn btn-secondary fw-bold mt-3 mb-2 texy-center">ADD STOCK</a>
          {% endif %}

          {% else %}
          {% if product.stock > 0 %}
          <a href="{% url 'cart:addtocart' product.id %}" class="btn btn-secondary fw-bold mt-3 mb-2 texy-center">ADD TO CART</a>
          {% else %}
          <h5>Out of stock</h5>
          {% endif %}
          {% endif %}

      </div>
    </div>
  </div>
</div>

 </div>
{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>LOGIN</title>
    {% endblock %}
{% block content %}
<center>
    <div class="container mt-5 p-3" style="margin-bottom:100px;">
<h2>Login here......</h2>
    <form method="post">
    {% csrf_token %}
    <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter username">
</div>
 <div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter password">
</div>
        <div class="mb-3">

  <input type="submit" class="form-control">
</div>
</form>
    {% if messages %}
<ul class="messages text-danger fs-4 text-capitalize">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    </div>
{% endblock %}
</body>
</html>

ecommerce/templates/order_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="container mt-5" style="margin-bottom:100px;">
<div class="row">
    <h4 class="text-center text-light mb-3">Name of the Customer: <i class="text-capitalize text-decoration-underline">{{user.username}}</i></h4>
    {% for i in orders %}
    <div class="card mb-5 p-3 mx-auto border border-2 border-dark shadow" style="max-width: 800px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{i.product.image.url}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Product name:{{i.product.name}}</h5>
          <h5 class="card-title">Price:<span class="text-primary">{{i.product.price}}</span></h5>
            <h6 class="card-title">Quantity:{{i.no_of_items}}</h6>
          <h6 class="card-title">Delivery_address:{{i.address}}</h6>
          <h6 class="card-title">Phone:{{i.phone_no}}</h6>

          <h5 class="card-title">Ordered On:{{i.ordered_date}}</h5>

          <h5 class="card-title">Delivery address:<span class="text-danger">{{i.delivery_status}}</span></h5>


      </div>
    </div>
  </div></div>
        {% endfor %}

</div>

 </div>
{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>LOGIN</title>
    {% endblock %}
{% block content %}
<center>
    <div class="container mt-2 p-3" style="margin-bottom:100px;">
<h2>Billing Details...</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="mb-3">
  <label  class="form-label">Address</label>
  <input type="text" class="form-control" name="a" placeholder="Enter Address">
</div>
 <div class="mb-3">
  <label  class="form-label">Phone number</label>
  <input type="number" class="form-control" name="p" placeholder="Enter phone number">
</div>
     <div class="mb-3">
  <label  class="form-label">Pin</label>
  <input type="number" class="form-control" name="pi" placeholder="Enter pinnumber">
</div>
             <div class="mb-3">

  <input type="submit" class="form-control">
</div>

        </form>

    </div>
{% endblock %}
</body>
</html>

ecommerce/templates/payment.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container mt-5 p-5 bg-light w-50" style="margin-bottom:100px;">

      <form action="http://127.0.0.1:8000/cart/status/{{payment.name}}" class="fs-4 text-center p-5" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_dVrWySYZeHoiH1" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="{{payment.id}}"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="MyShop"
    data-description="Shop smarter.shop here"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{payment.name}}"
    data-prefill.email="myshop@gmail.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>

    </div></div>
{% endblock %}
</body>
</html>

ecommerce/templates/payment_status.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container mt-5 p-5 bg-light w-50" style="margin-bottom:100px;">
        {% if status == True %}
         <h2 class="text-center">Payment Successful</h2>
        {% else %}
        <h2 class="text-center">Payment Failed.Please Try again...</h2>
        {% endif %}
  </div>
{% endblock %}
</body>
</html>

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="row mt-3">
        <div class="col-12">
    <img src="{{cat.image.url}}" height="400px" width="100%"></div>
</div>
<div class="row mt-3 px-3" style="margin-bottom:100px">
    <div class="col-12">
        <h1 class="text-center fw-bold text-light mt-5 mb-5">{{cat.name}}</h1>

        <p style="text-align:justify;line-height:2.5;" class="fs-5">{{cat.desc}}</p>
    </div>
</div>

<div class="container mt-5" style="margin-bottom:100px">

    <div class="row">
{% for i in product %}
        <div class="col-sm-4">
            <div class="card mx-auto border border-3 border-light" style="width: 20rem;">
  <img src="{{i.image.url}}"  height="200px" width="100%" class="card-img-top" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title mb-3">{{i.name}}</h5>
      <h5 class="card-title mb-3">{{i.price}}</h5>
    <a href="{% url 'shop:details' i.id %}" class="btn btn-secondary px-5 mb-2 fs-5">Details</a>
  </div>
</div></div>


{% endfor %}

    </div>

</div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="container mt-5" style="margin-bottom:100px;">
<h3 class="text-center">You have searched for <span class="text-light"> {{q}}</span></h3>
     </div>

<div class="container mt-5" style="margin-bottom:100px">

{% if product == None %}      <!--if no query entered by the user --->
    <h5 class="text-center">No Results Found</h5>
    {% else %}
    <div class="row">
{% for i in product %}
        <div class="col-sm-4">
            <div class="card mx-auto border border-3 border-light" style="width: 20rem;">
  <img src="{{i.image.url}}"  height="200px" width="100%" class="card-img-top" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title mb-3">{{i.name}}</h5>
      <h5 class="card-title mb-3">{{i.price}}</h5>
    <a href="{% url 'shop:details' i.id %}" class="btn btn-secondary px-5 mb-2 fs-5">Details</a>
  </div>
</div></div>
        {% empty %}     <!-- if product sequence empty -->
<h5 class="text-center">No Results Found</h5>
        {% endfor %}

    </div>
{% endif %}

 </div>
{% endblock %}